# Generated by Django 4.2 on 2023-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_menu_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descript',
            field=models.TextField(default='', max_length=500),
        ),
    ]
