# Generated by Django 4.2 on 2023-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_menu_descript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descript',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
