# Generated by Django 4.2 on 2023-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_menu_tab_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('photo', models.FileField(blank=True, default='main_app/img/no_photo', upload_to='')),
                ('price', models.FloatField(default=0)),
                ('special', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('menu', models.ManyToManyField(to='main_app.menu')),
            ],
        ),
    ]
