# Generated by Django 4.2 on 2023-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.FileField(blank=True, default='/static/main_app/img/no_photo.jpg', upload_to=''),
        ),
    ]
