# Generated by Django 4.2 on 2023-04-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_dishes_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descript',
            new_name='content',
        ),
    ]
