# Generated by Django 4.2 on 2023-04-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_dishes_options_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'ordering': ['title'], 'verbose_name': 'Блюда', 'verbose_name_plural': 'Блюдо'},
        ),
    ]
