# Generated by Django 4.2 on 2023-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_sale_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Імья')),
                ('e_mail', models.EmailField(default='empty@empty.com', max_length=254, verbose_name='пошта')),
                ('date', models.DateField(verbose_name='Дата прибуття')),
                ('phone', models.CharField(max_length=20)),
                ('time', models.TimeField(verbose_name='Час Прибуття')),
                ('message', models.TextField(max_length=1500, verbose_name='Повідомлення')),
                ('count_of_people', models.SmallIntegerField(default=1, verbose_name='Кількість людей')),
                ('status', models.CharField(max_length=255, verbose_name='Статус замовлення')),
            ],
            options={
                'verbose_name': 'Клиєнт',
                'verbose_name_plural': 'Клиєнти',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['positions', 'title', 'time_created'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Акції', 'verbose_name_plural': 'Акція'},
        ),
        migrations.AddField(
            model_name='sale',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_start',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_work',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='title',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_stop',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
