# Generated by Django 4.2 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_clients_galery_alter_menu_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=255, verbose_name='Опис')),
                ('price', models.SmallIntegerField(default=100, verbose_name='Ціна')),
                ('image', models.FileField(default='media/default_events.jpg', upload_to='', verbose_name='Фото')),
                ('date_start', models.DateField(auto_now=True)),
                ('date_stop', models.DateField()),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['date_start'],
            },
        ),
        migrations.AddField(
            model_name='galery',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
