# Generated by Django 4.2 on 2023-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_events_galery_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('content', models.TextField(max_length=1000, verbose_name='Опис')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('date_start', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повари',
                'ordering': ['title', 'date_start'],
            },
        ),
        migrations.AlterField(
            model_name='events',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Активне чи ні'),
        ),
    ]
