# Generated by Django 4.2 on 2023-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_chief_alter_events_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='chief',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
